apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: online-boutique-workspace
  namespace: online-boutique-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
