apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: online-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: image-registry.openshift-image-registry.svc:5000/online-boutique-cicd/adservice:main
